package com.deimos.perk.wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "wiloctWS_tagTrackingPortType", targetNamespace = "http://tags.ws.wiloct.dat.com")
public interface WiloctWSTagTrackingPortType {

	/**
	 * 
	 * @param in2
	 * @param in1
	 * @param in4
	 * @param in3
	 * @param in0
	 * @param in5
	 * @param in6
	 * @return returns int
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://tags.ws.wiloct.dat.com")
	@RequestWrapper(localName = "addTagTracking", targetNamespace = "http://tags.ws.wiloct.dat.com", className = "com.indoorlocation.wsclient.AddTagTracking")
	@ResponseWrapper(localName = "addTagTrackingResponse", targetNamespace = "http://tags.ws.wiloct.dat.com", className = "com.indoorlocation.wsclient.AddTagTrackingResponse")
	public int addTagTracking(
			@WebParam(name = "in0", targetNamespace = "http://tags.ws.wiloct.dat.com") String in0,
			@WebParam(name = "in1", targetNamespace = "http://tags.ws.wiloct.dat.com") Long in1,
			@WebParam(name = "in2", targetNamespace = "http://tags.ws.wiloct.dat.com") Double in2,
			@WebParam(name = "in3", targetNamespace = "http://tags.ws.wiloct.dat.com") Double in3,
			@WebParam(name = "in4", targetNamespace = "http://tags.ws.wiloct.dat.com") Integer in4,
			@WebParam(name = "in5", targetNamespace = "http://tags.ws.wiloct.dat.com") Integer in5,
			@WebParam(name = "in6", targetNamespace = "http://tags.ws.wiloct.dat.com") String in6);

}
