package com.deimos.perk.wsclient;

import java.net.MalformedURLException;
import java.net.URL;

import org.apache.log4j.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * wiloctWS_tagTracking service = new wiloctWS_tagTracking();
 * WiloctWSTagTrackingPortType portType = service.getWiloctWSTagTrackingHttpPort();
 * portType.addTagTracking(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "wiloctWS_tagTracking", targetNamespace = "http://tags.ws.wiloct.dat.com", wsdlLocation = "http://172.26.0.3:8080/wiloctWS/services/wiloctWS_tagTracking?wsdl")
public class WiloctWSTagTracking extends Service {

	private final static URL WILOCTWSTAGTRACKING_WSDL_LOCATION;
	private static Logger log = Logger.getLogger(WiloctWSTagTracking.class);

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.deimos.perk.wsclient.WiloctWSTagTracking.class.getResource(".");
			url = new URL(baseUrl,
					"http://172.26.0.3:8080/wiloctWS/services/wiloctWS_tagTracking?wsdl");
		} catch (MalformedURLException e) {
			log.warn("Failed to create URL for the wsdl Location: 'http://172.26.0.3:8080/wiloctWS/services/wiloctWS_tagTracking?wsdl', retrying as a local file");
			log.warn(e.getMessage());
		}
		WILOCTWSTAGTRACKING_WSDL_LOCATION = url;
	}

	public WiloctWSTagTracking(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public WiloctWSTagTracking() {
		super(WILOCTWSTAGTRACKING_WSDL_LOCATION, new QName(
				"http://tags.ws.wiloct.dat.com", "wiloctWS_tagTracking"));
	}

	/**
	 * 
	 * @return returns WiloctWSTagTrackingPortType
	 */
	@WebEndpoint(name = "wiloctWS_tagTrackingHttpPort")
	public WiloctWSTagTrackingPortType getWiloctWSTagTrackingHttpPort() {
		return super.getPort(new QName("http://tags.ws.wiloct.dat.com",
				"wiloctWS_tagTrackingHttpPort"),
				WiloctWSTagTrackingPortType.class);
	}

}
